using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using LKCamelot.model;
namespace LKCamelot.script.map
{
    public class InnerMap
    {
        public string Map;
        public string Dest;
        public List<Point2D> Locs;
        public Point2D ArriveLoc;

        public InnerMap(string Map, string Dest, Point2D ArriveLoc, List<Point2D> Locs)
        {
            this.Map = Map;
            this.Dest = Dest;
            this.Locs = Locs;
            this.ArriveLoc = ArriveLoc;
        }
    }

    public class Portal
    {
        public static List<InnerMap> Portals = new List<InnerMap>()
        {
            new InnerMap("Village1", "Loen", new Point2D(6,14), 
                new List<Point2D>(){ new Point2D(139,155)}),
            new InnerMap("Loen", "Village1", new Point2D(139,157), 
                new List<Point2D>(){ new Point2D(5,15)}),

            new InnerMap("Village1", "Arnold", new Point2D(5,18), 
                new List<Point2D>(){ new Point2D(65,158)}),
            new InnerMap("Arnold", "Village1", new Point2D(65,160), 
                new List<Point2D>(){ new Point2D(4,17)}),



            new InnerMap("Village1", "Miro1", new Point2D(1,1), 
                new List<Point2D>(){ new Point2D(135,55)}),
            new InnerMap("Miro1", "Village1", new Point2D(135,57), 
                new List<Point2D>(){ new Point2D(0,0)}),

            new InnerMap("Village1", "Biggun1", new Point2D(98,78), 
                new List<Point2D>(){ new Point2D(169,119)}),
            new InnerMap("Biggun1", "Village1", new Point2D(168,119), 
                new List<Point2D>(){ new Point2D(99,79)}),
            new InnerMap("Biggun1", "Biggun2", new Point2D(98,78), 
                new List<Point2D>(){ new Point2D(0,0)}),
            new InnerMap("Biggun2", "Biggun1", new Point2D(1,1), 
                new List<Point2D>(){ new Point2D(99,79)}),

            new InnerMap("Village1", "ELevel", new Point2D(29,32), 
                new List<Point2D>(){ new Point2D(99,128)}),
            new InnerMap("ELevel", "Village1", new Point2D(99,130), 
                new List<Point2D>(){ new Point2D(29,30)}),
            new InnerMap("ELevel", "010", new Point2D(73,8),
                new List<Point2D>(){ new Point2D(11,42)}),
            new InnerMap("010", "ELevel", new Point2D(11,44), 
                new List<Point2D>(){ new Point2D(73,6)}),
            new InnerMap("ELevel", "020", new Point2D(7,8),  
                new List<Point2D>(){ new Point2D(11,30)}),
            new InnerMap("020", "ELevel", new Point2D(11,32), 
                new List<Point2D>(){ new Point2D(7,6)}), 
            new InnerMap("ELevel", "030", new Point2D(14,11),
                new List<Point2D>(){ new Point2D(11,19)}),
            new InnerMap("030", "ELevel", new Point2D(11,21), 
                new List<Point2D>(){ new Point2D(14,9)}),
            new InnerMap("ELevel", "040", new Point2D(16,18),
                new List<Point2D>(){ new Point2D(22,12)}),
            new InnerMap("040", "ELevel", new Point2D(22,14), 
                new List<Point2D>(){ new Point2D(16,16)}),
            new InnerMap("ELevel", "050", new Point2D(87,46),
                new List<Point2D>(){ new Point2D(35,12)}),
            new InnerMap("050", "ELevel", new Point2D(35,14), 
                new List<Point2D>(){ new Point2D(87,44)}),
            new InnerMap("ELevel", "060", new Point2D(105,78),
                new List<Point2D>(){ new Point2D(47,18)}),
            new InnerMap("060", "ELevel", new Point2D(47,20), 
                new List<Point2D>(){ new Point2D(105,76)}), 
            new InnerMap("ELevel", "070", new Point2D(12,10),
                new List<Point2D>(){ new Point2D(47,30)}),
            new InnerMap("070", "ELevel", new Point2D(47,32), 
                new List<Point2D>(){ new Point2D(12,8)}),
            new InnerMap("ELevel", "080", new Point2D(109,81), 
                new List<Point2D>(){ new Point2D(47,42)}),
            new InnerMap("080", "ELevel", new Point2D(47,44), 
                new List<Point2D>(){ new Point2D(109,79)}), 


            new InnerMap("Village1", "ItemVillage", new Point2D(93,110), 
                new List<Point2D>(){ new Point2D(70,66)}),
            new InnerMap("ItemVillage", "Village1", new Point2D(70,68), 
                new List<Point2D>(){ new Point2D(93,108)}), 

            new InnerMap("ItemVillage", "ItemPigmy1", new Point2D(16,31), 
                new List<Point2D>(){ new Point2D(2,18)}),
            new InnerMap("ItemPigmy1", "ItemVillage", new Point2D(2,20), 
                new List<Point2D>(){ new Point2D(16,29)}), 
            new InnerMap("ItemPigmy1", "ItemPigmy2", new Point2D(10,12), 
                new List<Point2D>(){ new Point2D(41,27)}),
            new InnerMap("ItemPigmy2", "ItemPigmy1", new Point2D(41,29), 
                new List<Point2D>(){ new Point2D(10,10)}),
            new InnerMap("ItemPigmy2", "ItemPigmy3", new Point2D(7,27), 
                new List<Point2D>(){ new Point2D(67,8)}),
            new InnerMap("ItemPigmy3", "ItemPigmy2", new Point2D(67,10), 
                new List<Point2D>(){ new Point2D(7,25)}),

            new InnerMap("ItemVillage", "ItemZomby1", new Point2D(14,39), 
                new List<Point2D>(){ new Point2D(25,5)}),
            new InnerMap("ItemZomby1", "ItemVillage", new Point2D(25,7), 
                new List<Point2D>(){ new Point2D(12,39)}), 
            new InnerMap("ItemZomby1", "ItemZomby2", new Point2D(13,14), 
                new List<Point2D>(){ new Point2D(68,42)}),
            new InnerMap("ItemZomby2", "ItemZomby1", new Point2D(68,44), 
                new List<Point2D>(){ new Point2D(13,12)}), 
            new InnerMap("ItemZomby2", "ItemZomby3", new Point2D(13,12), 
                new List<Point2D>(){ new Point2D(64,20)}),
            new InnerMap("ItemZomby3", "ItemZomby2", new Point2D(64,22), 
                new List<Point2D>(){ new Point2D(13,10)}), 

            new InnerMap("ItemVillage", "ItemSkel1", new Point2D(20,31), 
                new List<Point2D>(){ new Point2D(186,4)}),
            new InnerMap("ItemSkel1", "ItemVillage", new Point2D(186,6), 
                new List<Point2D>(){ new Point2D(20,29)}), 
            new InnerMap("ItemSkel1", "ItemSkel2", new Point2D(12,13), 
                new List<Point2D>(){ new Point2D(42,21)}),
            new InnerMap("ItemSkel2", "ItemSkel1", new Point2D(42,23), 
                new List<Point2D>(){ new Point2D(11,12)}), 
            new InnerMap("ItemSkel2", "ItemSkel3", new Point2D(15,18), 
                new List<Point2D>(){ new Point2D(59,12)}),
            new InnerMap("ItemSkel3", "ItemSkel2", new Point2D(58,12), 
                new List<Point2D>(){ new Point2D(15,17)}), 

            new InnerMap("ItemVillage", "ItemButcher1", new Point2D(19,25), 
                new List<Point2D>(){ new Point2D(190,29)}),
            new InnerMap("ItemButcher1", "ItemVillage", new Point2D(190,31), 
                new List<Point2D>(){ new Point2D(19,23)}), 
            new InnerMap("ItemButcher1", "ItemButcher2", new Point2D(19,13), 
                new List<Point2D>(){ new Point2D(43,27)}),
            new InnerMap("ItemButcher2", "ItemButcher1", new Point2D(43,29), 
                new List<Point2D>(){ new Point2D(19,11)}),
            new InnerMap("ItemButcher2", "ItemButcher3", new Point2D(20,15), 
                new List<Point2D>(){ new Point2D(57,29)}),
            new InnerMap("ItemButcher3", "ItemButcher2", new Point2D(57,21), 
                new List<Point2D>(){ new Point2D(20,13)}),

            new InnerMap("ItemVillage", "ItemMummy1", new Point2D(18,19), 
                new List<Point2D>(){ new Point2D(193,186)}),
            new InnerMap("ItemMummy1", "ItemVillage", new Point2D(193,188), 
                new List<Point2D>(){ new Point2D(18,17)}), 
            new InnerMap("ItemMummy1", "ItemMummy2", new Point2D(13,11), 
                new List<Point2D>(){ new Point2D(47,34)}),
            new InnerMap("ItemMummy2", "ItemMummy1", new Point2D(13,9), 
                new List<Point2D>(){ new Point2D(18,17)}), 
            new InnerMap("ItemMummy2", "ItemMummy3", new Point2D(7,9), 
                new List<Point2D>(){ new Point2D(62,36)}),
            new InnerMap("ItemMummy3", "ItemMummy2", new Point2D(62,38), 
                new List<Point2D>(){ new Point2D(7,7)}), 

            new InnerMap("ItemVillage", "ItemStone1", new Point2D(16,14), 
                new List<Point2D>(){ new Point2D(177,160)}),
            new InnerMap("ItemStone1", "ItemVillage", new Point2D(177,162), 
                new List<Point2D>(){ new Point2D(16,12)}), 
            new InnerMap("ItemStone1", "ItemStone2", new Point2D(22,15), 
                new List<Point2D>(){ new Point2D(31,30)}),
            new InnerMap("ItemStone2", "ItemStone1", new Point2D(31,32), 
                new List<Point2D>(){ new Point2D(22,13)}), 
            new InnerMap("ItemStone2", "ItemStone3", new Point2D(16,18), 
                new List<Point2D>(){ new Point2D(44,34)}),
            new InnerMap("ItemStone3", "ItemStone2", new Point2D(44,36), 
                new List<Point2D>(){ new Point2D(16,16)}), 
            new InnerMap("ItemStone3", "ItemStone4", new Point2D(6,23), 
                new List<Point2D>(){ new Point2D(37,32)}),
            new InnerMap("ItemStone4", "ItemStone3", new Point2D(37,34), 
                new List<Point2D>(){ new Point2D(6,21)}), 

            new InnerMap("ItemVillage", "ItemDummy1", new Point2D(18,19), 
                new List<Point2D>(){ new Point2D(23,135)}),
            new InnerMap("ItemDummy1", "ItemVillage", new Point2D(23,136), 
                new List<Point2D>(){ new Point2D(18,17)}), 
            new InnerMap("ItemDummy1", "ItemDummy2", new Point2D(13,11), 
                new List<Point2D>(){ new Point2D(47,34)}),
            new InnerMap("ItemDummy2", "ItemDummy1", new Point2D(13,9), 
                new List<Point2D>(){ new Point2D(18,17)}), 
            new InnerMap("ItemDummy2", "ItemDummy3", new Point2D(7,9), 
                new List<Point2D>(){ new Point2D(62,36)}),
            new InnerMap("ItemDummy3", "ItemDummy2", new Point2D(62,38), 
                new List<Point2D>(){ new Point2D(7,7)}), 
            new InnerMap("ItemDummy3", "ItemDummy4", new Point2D(16,18), 
                new List<Point2D>(){ new Point2D(66,12)}),
            new InnerMap("ItemDummy4", "ItemDummy3", new Point2D(66,14), 
                new List<Point2D>(){ new Point2D(16,16)}), 
            new InnerMap("ItemDummy4", "ItemDummy5", new Point2D(6,23), 
                new List<Point2D>(){ new Point2D(37,32)}),
            new InnerMap("ItemDummy5", "ItemDummy4", new Point2D(37,34), 
                new List<Point2D>(){ new Point2D(6,21)}), 

            new InnerMap("ItemVillage", "ItemWarDummy1", new Point2D(18,19), 
                new List<Point2D>(){ new Point2D(38,142)}),
            new InnerMap("ItemWarDummy1", "ItemVillage", new Point2D(38,143), 
                new List<Point2D>(){ new Point2D(18,17)}), 
            new InnerMap("ItemWarDummy1", "ItemWarDummy2", new Point2D(13,11), 
                new List<Point2D>(){ new Point2D(47,34)}),
            new InnerMap("ItemWarDummy2", "ItemWarDummy1", new Point2D(13,9), 
                new List<Point2D>(){ new Point2D(18,17)}), 
            new InnerMap("ItemWarDummy2", "ItemWarDummy3", new Point2D(7,9), 
                new List<Point2D>(){ new Point2D(62,36)}),
            new InnerMap("ItemWarDummy3", "ItemWarDummy2", new Point2D(62,38), 
                new List<Point2D>(){ new Point2D(7,7)}), 
            new InnerMap("ItemWarDummy3", "ItemWarDummy4", new Point2D(16,18), 
                new List<Point2D>(){ new Point2D(66,12)}),
            new InnerMap("ItemWarDummy4", "ItemWarDummy3", new Point2D(66,14), 
                new List<Point2D>(){ new Point2D(16,16)}), 
            new InnerMap("ItemWarDummy4", "ItemWarDummy5", new Point2D(6,23), 
                new List<Point2D>(){ new Point2D(37,32)}),
            new InnerMap("ItemWarDummy5", "ItemWarDummy4", new Point2D(37,34), 
                new List<Point2D>(){ new Point2D(6,21)}), 

            new InnerMap("ItemVillage", "ItemHardboil1", new Point2D(18,19), 
                new List<Point2D>(){ new Point2D(13,45)}),
            new InnerMap("ItemHardboil1", "ItemVillage", new Point2D(13,46), 
                new List<Point2D>(){ new Point2D(18,17)}), 
            new InnerMap("ItemHardboil1", "ItemHardboil2", new Point2D(13,11), 
                new List<Point2D>(){ new Point2D(47,34)}),
            new InnerMap("ItemHardboil2", "ItemHardboil1", new Point2D(13,9), 
                new List<Point2D>(){ new Point2D(18,17)}), 
            new InnerMap("ItemHardboil2", "ItemHardboil3", new Point2D(7,9), 
                new List<Point2D>(){ new Point2D(62,36)}),
            new InnerMap("ItemHardboil3", "ItemHardboil2", new Point2D(62,38), 
                new List<Point2D>(){ new Point2D(7,7)}), 
            new InnerMap("ItemHardboil3", "ItemHardboil4", new Point2D(16,18), 
                new List<Point2D>(){ new Point2D(66,12)}),
            new InnerMap("ItemHardboil4", "ItemHardboil3", new Point2D(66,14), 
                new List<Point2D>(){ new Point2D(16,16)}), 
            new InnerMap("ItemHardboil4", "ItemHardboil5", new Point2D(6,23), 
                new List<Point2D>(){ new Point2D(37,32)}),
            new InnerMap("ItemHardboil5", "ItemHardboil4", new Point2D(37,34), 
                new List<Point2D>(){ new Point2D(6,21)}), 

            new InnerMap("ItemVillage", "ItemGolem1", new Point2D(18,19), 
                new List<Point2D>(){ new Point2D(7,178)}),
            new InnerMap("ItemGolem1", "ItemVillage", new Point2D(7,179), 
                new List<Point2D>(){ new Point2D(18,17)}), 
            new InnerMap("ItemGolem1", "ItemGolem2", new Point2D(13,11), 
                new List<Point2D>(){ new Point2D(47,34)}),
            new InnerMap("ItemGolem2", "ItemGolem1", new Point2D(13,9), 
                new List<Point2D>(){ new Point2D(18,17)}), 
            new InnerMap("ItemGolem2", "ItemGolem3", new Point2D(7,9), 
                new List<Point2D>(){ new Point2D(62,36)}),
            new InnerMap("ItemGolem3", "ItemGolem2", new Point2D(62,38), 
                new List<Point2D>(){ new Point2D(7,7)}), 
            new InnerMap("ItemGolem3", "ItemGolem4", new Point2D(16,18), 
                new List<Point2D>(){ new Point2D(66,12)}),
            new InnerMap("ItemGolem4", "ItemGolem3", new Point2D(66,14), 
                new List<Point2D>(){ new Point2D(16,16)}), 
            new InnerMap("ItemGolem4", "ItemGolem5", new Point2D(6,23), 
                new List<Point2D>(){ new Point2D(37,32)}),
            new InnerMap("ItemGolem5", "ItemGolem4", new Point2D(37,34), 
                new List<Point2D>(){ new Point2D(6,21)}), 

            new InnerMap("Village1", "Skel1", new Point2D(50,13), 
                new List<Point2D>(){ new Point2D(139,134)}),
            new InnerMap("Skel1", "Village1", new Point2D(138,136), 
                new List<Point2D>(){ new Point2D(50,11)}), 
            new InnerMap("Skel1", "Skel2", new Point2D(12,14), 
                new List<Point2D>(){ new Point2D(13,47)}),
            new InnerMap("Skel2", "Skel1", new Point2D(13,49), 
                new List<Point2D>(){ new Point2D(12,12)}), 
            new InnerMap("Skel2", "Skel3", new Point2D(34,14), 
                new List<Point2D>(){ new Point2D(48,42)}),
            new InnerMap("Skel3", "Skel2", new Point2D(48,44), 
                new List<Point2D>(){ new Point2D(34,12)}), 
            new InnerMap("Skel3", "Skel4", new Point2D(33,24), 
                new List<Point2D>(){ new Point2D(33,49)}),
            new InnerMap("Skel4", "Skel3", new Point2D(33,51), 
                new List<Point2D>(){ new Point2D(33,22)}), 
            new InnerMap("Skel4", "Skel5", new Point2D(14,21), 
                new List<Point2D>(){ new Point2D(32,35)}),
            new InnerMap("Skel5", "Skel4", new Point2D(32,37), 
                new List<Point2D>(){ new Point2D(14,19)}),   //skel5 out 52:54


            new InnerMap("Village1", "Weakly1", new Point2D(11,19), 
                new List<Point2D>(){ new Point2D(65,122)}),
            new InnerMap("Weakly1", "Village1", new Point2D(66,123), 
                new List<Point2D>(){ new Point2D(11,17)}),
            new InnerMap("Weakly1", "Weakly2", new Point2D(51,14), 
                new List<Point2D>(){ new Point2D(50,44)}),
            new InnerMap("Weakly2", "Weakly1", new Point2D(50,46), 
                new List<Point2D>(){ new Point2D(51,12)}), 
            new InnerMap("Weakly2", "Weakly3", new Point2D(53,15), 
                new List<Point2D>(){ new Point2D(38,53)}),
            new InnerMap("Weakly3", "Weakly2", new Point2D(38,55), 
                new List<Point2D>(){ new Point2D(53,13)}), 
            new InnerMap("Weakly3", "Weakly4", new Point2D(9,54), 
                new List<Point2D>(){ new Point2D(9,34)}),
            new InnerMap("Weakly4", "Weakly3", new Point2D(9,36), 
                new List<Point2D>(){ new Point2D(9,52)}), 
            new InnerMap("Weakly4", "Weakly5", new Point2D(9,11), 
                new List<Point2D>(){ new Point2D(52,51)}),
            new InnerMap("Weakly5", "Weakly4", new Point2D(52,53), 
                new List<Point2D>(){ new Point2D(9,9)}), 

            new InnerMap("Golem", "Golem1", new Point2D(1,1), 
                new List<Point2D>(){ new Point2D(41,49)}),
            new InnerMap("Golem1", "Golem", new Point2D(41,48), 
                new List<Point2D>(){ new Point2D(0,0)}),
            new InnerMap("Golem", "Golem3", new Point2D(27,1), 
                new List<Point2D>(){ new Point2D(49,5)}),
            new InnerMap("Golem3", "Golem", new Point2D(48,5), 
                new List<Point2D>(){ new Point2D(27,0)}),
            new InnerMap("Golem1", "Golem2", new Point2D(33,27), 
                new List<Point2D>(){ new Point2D(35,49)}),
            new InnerMap("Golem2", "Golem1", new Point2D(35,48), 
                new List<Point2D>(){ new Point2D(33,26)}),

            new InnerMap("Golem1", "Golem12", new Point2D(1,2), 
                new List<Point2D>(){ new Point2D(40,0)}),
            new InnerMap("Golem12", "Golem1", new Point2D(40,1), 
                new List<Point2D>(){ new Point2D(0,2)}),

            new InnerMap("TreasureLand", "Great", new Point2D(19,22), 
                new List<Point2D>(){ new Point2D(45,71)}),
            new InnerMap("Great", "TreasureLand", new Point2D(45,72), 
                new List<Point2D>(){ new Point2D(19,21)}),

    /*        new InnerMap("Golem2", "Golem3", new Point2D(27,1), 
                new List<Point2D>(){ new Point2D(18,49)}),
            new InnerMap("Golem3", "Golem2", new Point2D(18,48), 
                new List<Point2D>(){ new Point2D(27,0)}),
            new InnerMap("Golem3", "Golem12", new Point2D(1,2), 
                new List<Point2D>(){ new Point2D(25,29)}),
            new InnerMap("Golem12", "Golem3", new Point2D(26,29), 
                new List<Point2D>(){ new Point2D(0,2)}),*/
        };
    }
}
